export const wordActionsType = {
    ADD_WORD: "ADD_WORD",
    DELETE_WORDS: "DELETE_WORDS",
    EDIT_WORD: "EDIT_WORD",
    TOGGLE_SELECTED_WORD: "TOGGLE_SELECTED_WORD",
};

export const categoryActionsType = {
    ADD_CATEGORY: "ADD_CATEGORY",
    DELETE_CATEGORIES: "DELETE_CATEGORIES",
    EDIT_CATEGORY: "EDIT_CATEGORY",
    TOGGLE_SELECTED_CATEGORIES: "TOGGLE_SELECTED_CATEGORIES",
};

export const formActionsType = {
    TOOGLE_OVERLAY_VIEW: "TOOGLE_OVERLAY_VIEW",
    SET_RU_WORD: "SET_RU_WORD",
    SET_ENG_WORD: "SET_ENG_WORD",
    SET_CATEGORY_WORD: "SET_CATEGORY_WORD",
    SET_STATUS_WORD: "SET_STATUS_WORD",
    SET_EXAMPLES_WORD: "SET_EXAMPLES_WORD",
    SET_TYPE: "SET_TYPE",
    SET_TITLE_CATEGORY: "SET_TITLE_CATEGORY",
    SET_EXMAPLE_WORD_IN_CATEGORY: "SET_EXMAPLE_WORD_IN_CATEGORY",
};